all:
	gcc -Wall -g Main.c func1.c func2.c func3.c func4.c func5.c func6.c func7.c func8.c func9.c func10.c func11.c func12.c func13.c leitura.c impressao.c fornecidas.c utils.c grafo.c csv_utils.c grafo_builder.c grafo_mst.c -o programaTrab
	
copy:
	cp -f ./intactos/*.bin ./

run:
	./programaTrab
